dotfiles_dir = "code/alxreed/dotfiles"

[settings]

[settings.dots]
alacritty = { source = "terminals/alacritty", target = ".config/alacritty" }
ghostty = { source = "terminals/ghostty", target = ".config/ghostty" }
zsh = { source = "zsh/zshrc", target = ".zshrc" }
zsh_env = { source = "zsh/zshenv", target = ".zshenv" }
gitconfig = { source = "git/gitconfig", target = ".gitconfig" }
pictures = { source = "pictures", target = "Images/pictures" }

# Cursor
dmz = { source = "cursor", target = ".icons/default"}

# launcher
onagre = { source = "launchers/onagre", target = ".config/onagre" }
wofi = { source = "launchers/wofi", target = ".config/wofi" }

# wm
sway = { source = "wm/sway", target = ".config/sway" }
mako = { source = "wm/wob", target = ".config/wob" }
wlogout = { source = "wm/wlogout", target = ".config/wlogout" }
swaylock = { source = "wm/swaylock", target = ".config/swaylock" }
niri = { source = "wm/niri", target = ".config/niri" }

# shell
noctalia = { source = "shell/noctalia", target = ".config/noctalia" }

[profiles.ubuntu]
[profiles.arch]

[profiles.ubuntu.dots]
starship = { source = "zsh/starship.toml", target = ".config/starship/starship.toml" }
neofetch = { source = "neofetch/ubuntu", target = ".config/neofetch" }

[profiles.arch.dots]
starship = { source = "zsh/starship.toml", target = ".config/starship.toml" }
neofetch = { source = "neofetch/arch", target = ".config/neofetch" }
