# Java
{% if "ubuntu" in profiles %}
  export JAVA_HOME='/usr/lib/jvm/java-18-openjdk-amd64'
{% elif "arch" in profiles %}
  export JAVA_HOME='/usr/lib/jvm/default'
{% endif %}

# Intellij
export IDEA_JDK='/opt/intellij-idea-ultimate-edition/jbr'

# Rust
export PATH="$PATH:$HOME/.cargo/bin"

# Flutter
export PATH="$PATH":"$HOME/.pub-cache/bin"