# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Editor
export VISUAL="nvim"

# Antigen 
source /usr/share/zsh/share/antigen.zsh 
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions
antigen bundle zuxfoucault/colored-man-pages_mod
antigen bundle zsh-users/zsh-completions
antigen apply

export EDITOR="vim"

# Aliases
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias status='systemctl status'
alias restart='sudo systemctl restart'

# Get External IP / local IPs
alias ip="curl ipinfo.io/ip"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias speedtest="wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip"

# Quickly serve the current directory as HTTP
alias serve='ruby -run -e httpd . -p 8000'  # Or python -m SimpleHTTPServer :)

# lock screen
alias lock="gnome-screensaver-command -l"

# app running
alias apps="ps -A"

# Pushing/pulling to origin remote
alias gpo="git push origin"
alias glo="git pull origin"

# Pushing/pulling to origin remote, master branch
alias glom="git pull origin master"
alias glod="git pull origin develop"

# Commit amend
alias gcamno="git commit --amend --no-edit"
alias gcam="git commit --amend"

# connect to ubastion
alias bastion="ssh ubastion.adeo.com -l 20013176"

# update && upgrade packages
{% if "ubuntu" in profiles %}
  alias up="sudo apt update && sudo apt upgrade && sudo snap refresh"
{% elif "arch" in profiles %}
  alias up="yay -Syu"

  prompt off
{% endif %}

eval "$(starship init zsh)"
